[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# employees\-app

## public
> leftSide=`true`


### index\.html
- FILE
<pre>public/index.html</pre>

## src

### index\.js
- FILE
<pre>src/index.js</pre>

### components

#### app

##### App\.js
- FILE
<pre>src/components/app/App.js</pre>

###### app\-info
> collapsed=`true`


####### app\-info\.js
- FILE
<pre>src/components/app-info/app-info.js</pre>

####### app\-info\.css
- FILE
<pre>src/components/app-info/app-info.css</pre>

###### div

####### search\-panel
> collapsed=`true`


######## search\-panel\.js
- FILE
<pre>src/components/search-panel/search-panel.js</pre>

######## search\-panel\.css
- FILE
<pre>src/components/search-panel/search-panel.css</pre>

####### app\-filter
> collapsed=`true`


######## app\-filter\.js
- FILE
<pre>src/components/app-filter/app-filter.js</pre>

######## app\-filter\.css
- FILE
<pre>src/components/app-filter/app-filter.css</pre>

###### employees\-list

####### employees\-list\.js
- FILE
<pre>src/components/employees-list/employees-list.js</pre>

######## employees\-list\-item

######### employees\-list\-item\.js
- FILE
<pre>src/components/employees-list-item/employees-list-item.js</pre>

######### employees\-list\-item\.css
- FILE
<pre>src/components/employees-list-item/employees-list-item.css</pre>

####### employees\-list\.css
- FILE
<pre>src/components/employees-list/employees-list.css</pre>

###### employees\-add\-form

####### employees\-add\-form\.js
- FILE
<pre>src/components/employees-add-form/employees-add-form.js</pre>

####### employees\-add\-form\.css
- FILE
<pre>src/components/employees-add-form/employees-add-form.css</pre>

##### app\.css
- FILE
<pre>src/components/app/app.css</pre>
